Use GitHub actions conventional hyphen for input names
isort/isort-action pull request #59
Opened 2022-10-29 16:29 UTC by jdufresne

Looking through the GitHub workflow docs, all arguments use a kebab-case, not camelCase. As well all of the default actions use kebab-case, for example, checkout:

https://github.com/actions/checkout

Follow community conventions.

The old camelCase arguments will continue to work for backward compatibility. These arguments are now marked as deprecated and should eventually be removed in a future version.

2022-10-29 22:04 UTC, jamescurtin requested changes
Thank you for helping to standardize here! It appears as if this change will modify a few default values however. This LGTM once the defaults for the new inputs match the corresponding deprecated input defaults.

2022-10-29 22:14 UTC, jdufresne commented on action.yml
> +    default: null
Yes, this is done to allow cascading the variable to whichever one is set.

For example, if a user supplies `isortVersion`, but `isort-version` defaults to `latest`, then then expression `${{ inputs.isort-version || inputs.isortVersion }}` will evaluate to `latest` rather than the expected set `isortVersion` value.

In practice, the default will remain `latest` through the cascading.

2022-10-29 22:16 UTC, jamescurtin commented on action.yml
> +    default: null
Got it; can you add comments to the effect? When it comes time to remove the deprecated options in a future release, that makes it less likely to forget to update the defaults.

2022-10-29 23:34 UTC, jdufresne commented on action.yml
> +    default: null
Good idea. Done in the latest revision.

2022-11-03 02:19 UTC, jamescurtin approved these changes

2022-11-03 02:20 UTC, merged